create table SYS_USER
(
  ID bigint not null primary key,
  NAME varchar(50) null,
  SALT varchar(100) null,
  PASSWORD varchar(100) null,
  EDITABLE varchar(1) null,
  ENABLE varchar(1) null,
  REMARK varchar(200) null,
  CREATE_USER bigint null,
  CREATE_TIME varchar(19) null,
  MODIFY_USER bigint null,
  MODIFY_TIME varchar(19) null
);

create table SYS_ROLE
(
  ID bigint not null primary key,
  NAME varchar(50) null,
  EDITABLE varchar(1) null,
  ENABLE varchar(1) null,
  REMARK varchar(200) null,
  CREATE_USER bigint null,
  CREATE_TIME varchar(19) null,
  MODIFY_USER bigint null,
  MODIFY_TIME varchar(19) null
);

CREATE TABLE SYS_AUTHORITY (
  ID BIGINT PRIMARY KEY,
  NAME   VARCHAR(80),
  TYPE VARCHAR(1),
  PARENT_ID BIGINT,
  URL VARCHAR(200),
  ICON_CLS VARCHAR(50),
  SEQUENCE INT,
  ENABLE VARCHAR(1),
  REMARK VARCHAR(200),
  CREATE_USER BIGINT,
  CREATE_TIME VARCHAR(19),
  MODIFY_USER BIGINT,
  MODIFY_TIME VARCHAR(19)
);

CREATE TABLE SYS_USER_ROLE
(
  ID BIGINT PRIMARY KEY,
  USER_ID   BIGINT,
  ROLE_ID BIGINT,
  CREATE_USER BIGINT,
  CREATE_TIME VARCHAR(19),
  MODIFY_USER BIGINT,
  MODIFY_TIME VARCHAR(19)
);

CREATE TABLE SYS_ROLE_AUTHORITY
(
  ID BIGINT PRIMARY KEY,
  ROLE_ID   BIGINT,
  AUTHORITY_ID BIGINT,
  CREATE_USER BIGINT,
  CREATE_TIME VARCHAR(19),
  MODIFY_USER BIGINT,
  MODIFY_TIME VARCHAR(19)
);

CREATE TABLE SYS_ERROR_CODE
(
  ID BIGINT PRIMARY KEY,
  CODE   VARCHAR(20),
  MESSAGE VARCHAR(200),
  LANG VARCHAR(10),
  CREATE_USER BIGINT,
  CREATE_TIME VARCHAR(19),
  MODIFY_USER BIGINT,
  MODIFY_TIME VARCHAR(19)
);

CREATE TABLE SYS_PARAM
(
  ID BIGINT PRIMARY KEY,
  CODE  VARCHAR(60),
  CATEGORY VARCHAR(60),
  VALUE VARCHAR(60),
  REMARK VARCHAR(200),
  CREATE_USER BIGINT,
  CREATE_TIME VARCHAR(19),
  MODIFY_USER BIGINT,
  MODIFY_TIME VARCHAR(19)
);

CREATE TABLE SYS_TASK
(
  ID BIGINT PRIMARY KEY,
  NAME   VARCHAR(120),
  CATEGORY VARCHAR(60),
  CLASS_NAME VARCHAR(200),
  CRON_EXPRESSION VARCHAR(200),
  SEQUENCE INT,
  RUN_STATUS VARCHAR(1),
  ENABLE VARCHAR(1),
  REMARK VARCHAR(200),
  CREATE_USER BIGINT,
  CREATE_TIME VARCHAR(19),
  MODIFY_USER BIGINT,
  MODIFY_TIME VARCHAR(19)
);

CREATE TABLE SYS_TASK_LOG
(
  ID BIGINT PRIMARY KEY,
  TASK_ID   BIGINT,
  TASK_NAME VARCHAR(120),
  TASK_CATEGORY VARCHAR(60),
  TASK_CLASS_NAME VARCHAR(200),
  TASK_CRON_EXPRESSION VARCHAR(200),
  START_TIME VARCHAR(19),
  END_TIME VARCHAR(19),
  RESULT VARCHAR(1),
  CREATE_USER BIGINT,
  CREATE_TIME VARCHAR(19),
  MODIFY_USER BIGINT,
  MODIFY_TIME VARCHAR(19)
);

CREATE TABLE SYS_LOGIN_LOG
(
  ID BIGINT PRIMARY KEY ,
  USER_ID   BIGINT,
  USER_NAME VARCHAR(50),
  IP VARCHAR(50),
  LOGIN_TIME VARCHAR(19),
  LOGOUT_TIME VARCHAR(19),
  RESULT VARCHAR(1),
  REMASK VARCHAR(200),
  CREATE_USER BIGINT,
  CREATE_TIME VARCHAR(19),
  MODIFY_USER BIGINT,
  MODIFY_TIME VARCHAR(19)
);