CREATE TABLE sys_authority
(
    AUTHORITY_ID VARCHAR(18) PRIMARY KEY NOT NULL,
    AUTHORITY_CODE VARCHAR(60),
    AUTHORITY_NAME VARCHAR(60),
    AUTHORITY_TYPE VARCHAR(50),
    AUTHORITY_RECHECK VARCHAR(1),
    AUTHORITY_LEADER_AUTH VARCHAR(1),
    AUTHORITY_LEADER_CHECK VARCHAR(1),
    AUTHORITY_SEQUENCE INT(11),
    AUTHORITY_DESC VARCHAR(200),
    AUTHORITY_STATUS VARCHAR(2),
    AUTHORITY_PARENT_ID VARCHAR(18),
    AUTHORITY_VIEW VARCHAR(100),
    AUTHORITY_ACTION VARCHAR(255)
);
CREATE TABLE sys_error_code
(
    ERROR_CODE VARCHAR(100) PRIMARY KEY NOT NULL,
    ERROR_MESSAGE VARCHAR(200)
);
CREATE TABLE sys_organization
(
    ORG_ID VARCHAR(18) PRIMARY KEY NOT NULL,
    ORG_NAME VARCHAR(50),
    ORG_STATUS VARCHAR(1),
    ORG_UPDATE_TIME VARCHAR(20)
);
CREATE TABLE sys_param
(
    PARAM_TYPE_ID VARCHAR(60) PRIMARY KEY NOT NULL,
    PARAM_GROUP_ID VARCHAR(60),
    PARAM_CODE VARCHAR(60),
    PARAM_DESC VARCHAR(200)
);
CREATE TABLE sys_role
(
    ROLE_ID VARCHAR(18) PRIMARY KEY NOT NULL,
    ROLE_NAME VARCHAR(50),
    ROLE_STATUS VARCHAR(2),
    ROLE_DESC VARCHAR(200)
);
CREATE TABLE sys_role_auth
(
    ROLE_ID VARCHAR(18) NOT NULL,
    AUTH_ID VARCHAR(18) NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (ROLE_ID, AUTH_ID)
);
CREATE TABLE sys_role_user
(
    ROLE_ID VARCHAR(18) NOT NULL,
    USER_ID VARCHAR(18) NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (ROLE_ID, USER_ID)
);
CREATE TABLE sys_user
(
    USER_ID VARCHAR(18) PRIMARY KEY NOT NULL,
    USER_NAME VARCHAR(50),
    USER_PASSWORD VARCHAR(50),
    USER_ORG VARCHAR(50),
    USER_STATUS VARCHAR(2),
    USER_DESC VARCHAR(200)
);
CREATE TABLE sys_user_login_record
(
    ID VARCHAR(18) PRIMARY KEY NOT NULL,
    USER_ID VARCHAR(18),
    LOGIN_TIME VARCHAR(20),
    LOGOUT_TIME VARCHAR(20),
    LOGIN_IP VARCHAR(20),
    LOGIN_RESULT VARCHAR(1)
);
CREATE TABLE sys_task
(
    ID VARCHAR(5) PRIMARY KEY NOT NULL,
    NAME VARCHAR(122),
    TASK_GROUP VARCHAR(20),
    CLASS_NAME VARCHAR(122),
    STATUS VARCHAR(1),
    CRON_EXPRESSION VARCHAR(122),
    DESCRIPTION VARCHAR(122),
    LEVEL VARCHAR(1),
    ENABLE VARCHAR(1),
    SEQ INTEGER
);
CREATE TABLE sys_task_log
(
  START_TIME VARCHAR(20) NOT NULL,
  END_TIME VARCHAR(20),
  TASK_ID VARCHAR(5) NOT NULL,
  TASK_NAME VARCHAR(122),
  TASK_GROUP VARCHAR(20),
  TASK_CLASS VARCHAR(122),
  TASK_CRON VARCHAR(122),
  TASK_DESC VARCHAR(122),
  TASK_RESULT VARCHAR(1),
  PRIMARY KEY (TASK_ID, START_TIME)
);
CREATE TABLE sys_serial_number
(
    SN_ID VARCHAR(50) PRIMARY KEY NOT NULL,
    SN_CURRENT VARCHAR(30),
    SN_INCREASE VARCHAR(3),
    SN_MAX VARCHAR(30),
    SN_SIZE VARCHAR(3),
    SN_LENGTH INT(11),
    SN_DESC VARCHAR(80)
);
CREATE TABLE base_department
(
    ID VARCHAR(12) PRIMARY KEY NOT NULL,
    NAME VARCHAR(80),
    PARENT_ID VARCHAR(12),
    STATUS VARCHAR(1)
);
CREATE TABLE base_position
(
    ID VARCHAR(12) PRIMARY KEY NOT NULL,
    NAME VARCHAR(80),
    STATUS VARCHAR(1),
    DESCRIPTION VARCHAR(200)
);
CREATE TABLE biz_department_position
(
    DEPARTMENT_ID VARCHAR(12) NOT NULL,
    POSITION_ID VARCHAR(12) NOT NULL,
    MAX_NUM INT(11) DEFAULT '0' NOT NULL,
    DESCRIPTION VARCHAR(200),
    CONSTRAINT `PRIMARY` PRIMARY KEY (DEPARTMENT_ID, POSITION_ID)
);